USE SLRG_BERN_JUGEND;

GO

DECLARE @var0 nvarchar;
DECLARE @var1 nvarchar;
DECLARE @var2 nvarchar;
DECLARE @var3 nvarchar;
DECLARE @var4 nvarchar;
DECLARE @var5 bit;

INSERT INTO USERS
(Username,[Password],Salt,Email,[Admin]) VALUES
(@var0,@var1,@var2,@var3,@var4,@var5);

GO

DECLARE @var6 int;
DECLARE @var7 int;
SET @var6 = (SELECT TOP(1) PK FROM USERS ORDER BY PK DESC);

DECLARE ADMIN_CURSOR CURSOR FOR
	(SELECT PK FROM PEOPLE);
	OPEN ADMIN_CURSOR;
		FETCH NEXT FROM ADMIN_CURSOR INTO @var7;
		WHILE @@FETCH_STATUS = 0
		BEGIN
			INSERT INTO PERMISSIONS
			(FK_U,FK_P)VALUES
			(@var6,@var7);
			FETCH NEXT FROM ADMIN_CURSOR INTO @PerID
		END
	CLOSE ADMIN_CURSOR
DEALLOCATE ADMIN_CURSOR;