Use SLRG_BERN_JUGEND;

Go

DECLARE @PerID INT;
DECLARE @Admin_ID INT;
SET @Admin_ID = (SELECT PK FROM "USERS" WHERE Username = 'felix.neidhart');

DECLARE ADMIN_CURSOR CURSOR FOR
	(SELECT PK FROM PEOPLE);
	OPEN ADMIN_CURSOR;
		FETCH NEXT FROM ADMIN_CURSOR INTO @PerID;
		WHILE @@FETCH_STATUS = 0
		BEGIN
			INSERT INTO PERMISSIONS
			(FK_U,FK_P)VALUES
			(@Admin_ID,@PerID);
			FETCH NEXT FROM ADMIN_CURSOR INTO @PerID
		END
	CLOSE ADMIN_CURSOR
DEALLOCATE ADMIN_CURSOR;