CREATE DATABASE SLRG_BERN_JUGEND;

GO

USE SLRG_BERN_JUGEND;

CREATE TABLE PEOPLE (
PK INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Prename NVARCHAR(32) NOT NULL,
Lastname NVARCHAR(32) NOT NULL,
Birthday DATE NULL,
Male BIT NOT NULL,
Active BIT NOT NULL,
PhoneNr NVARCHAR(12) NULL, /*+41791234567*/
Email NVARCHAR(64) NULL
);

CREATE TABLE DISCIPLINES (
PK INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Discipline NVARCHAR(32) NOT NULL,
Meters INT NOT NULL
);

CREATE TABLE TIMES (
PK INT NOT NULL PRIMARY KEY IDENTITY(1,1),
FK_P INT NOT NULL FOREIGN KEY REFERENCES PEOPLE(PK) ON DELETE CASCADE,
FK_D INT NOT NULL FOREIGN KEY REFERENCES DISCIPLINES(PK) ON DELETE CASCADE,
Seconds DECIMAL(5,2) NOT NULL,
[Date] DATE NOT NULL
);

CREATE TABLE [USERS] (
PK INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Username NVARCHAR(32) NOT NULL,
[Password] NVARCHAR(64) NOT NULL,
Salt NVARCHAR(64) NOT NULL,
Email NVARCHAR(32) NOT NULL,
[Admin] BIT NOT NULL
);

CREATE TABLE [PERMISSIONS] (
PK INT NOT NULL PRIMARY KEY IDENTITY(1,1),
FK_U INT NOT NULL FOREIGN KEY REFERENCES [USERS](PK) ON DELETE CASCADE,
FK_P INT NOT NULL FOREIGN KEY REFERENCES PEOPLE(PK) ON DELETE CASCADE
);

INSERT INTO [USERS]
(Username,[Password],Salt,Email,[Admin]) VALUES
('felix.neidhart','38c07f88485a848e077c1415a3fd6dc44bc877ac801f1fa36cb5d1cba5b61fdc','287f8fe7848fb5f3cae74ac7fb3fff93503b26fbb2b5c8cd69a1dc49152a2a7d','felix.neidhart@gmail.com',1),
('thomas.waelti','67dc90102cb1a32f7b8b3459a5c89c4a24bbdeb72960263bccf2fc20209e42df','6463ef16db7f0809c2384c16eb9f1b97ffb94d3e3a648fbf41b342ece4004740','thomaswaelti@hispeed.ch',0);

GO

/*Create Logins*/
USE master
GO
CREATE LOGIN [db_read] WITH PASSWORD='read-3087', DEFAULT_DATABASE=[SLRG_BERN_JUGEND], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO
CREATE LOGIN [db_write] WITH PASSWORD='write-3087', DEFAULT_DATABASE=[SLRG_BERN_JUGEND], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO

/*Create User*/
USE [SLRG_BERN_JUGEND]
GO
CREATE USER [db_read] FOR LOGIN [db_read] WITH DEFAULT_SCHEMA=[dbo]
GO
GRANT SELECT ON SLRG_BERN_JUGEND.PEOPLE TO db_read;
GRANT SELECT ON SLRG_BERN_JUGEND.DISCIPLINES TO db_read;
GRANT SELECT ON SLRG_BERN_JUGEND.TIMES TO db_read;
GRANT SELECT ON SLRG_BERN_JUGEND.USERS TO db_read;
GRANT SELECT ON SLRG_BERN_JUGEND.PERMISSIONS TO db_read;
GO
CREATE USER [db_write] FOR LOGIN [db_write] WITH DEFAULT_SCHEMA=[dbo]
GO
GRANT SELECT,INSERT,UPDATE,DELETE ON SLRG_BERN_JUGEND.PEOPLE TO db_write;
GRANT SELECT,INSERT,UPDATE,DELETE ON SLRG_BERN_JUGEND.DISCIPLINES TO db_write;
GRANT SELECT,INSERT,UPDATE,DELETE ON SLRG_BERN_JUGEND.TIMES TO db_write;
GRANT SELECT,INSERT,UPDATE,DELETE ON SLRG_BERN_JUGEND.USERS TO db_write;
GRANT SELECT,INSERT,UPDATE,DELETE ON SLRG_BERN_JUGEND.PERMISSIONS TO db_write;
